name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - '2.x'

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version:
          - '8.3'
          - '8.4'
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Composer install
        uses: ramsey/composer-install@v3

      - name: 'Run tests'
        run: 'make -j -O test'

      - name: 'Send code coverage'
        if: ${{ matrix.php-version == '8.3' }}
        uses: codecov/codecov-action@v5
